export interface Amendment {
  id: string
  kind: "bootstrap" | "transition" | "retirement" | "correction" | "supersession"
  contractId: string
  baseRevision: string
  targets: readonly string[]
  beforeFingerprint: string | null
  afterFingerprint: string
  rationale: string
  compatibility: string
  migration: string
  supersedes: string | null
  pullRequest: string | null
}

export const amendments: readonly Amendment[] = Object.freeze([
  {
    id: "BOOTSTRAP-001",
    kind: "bootstrap",
    contractId: "GOV-003",
    baseRevision: "e078dd491004795c99b37121471152e41bb17194",
    targets: [
      "validation/contracts.ts",
      "validation/exceptions.ts",
      "validation/nessa/check-metadata.ts",
    ],
    beforeFingerprint: null,
    afterFingerprint: "4beb348bbeaa1d82da83a9d49b58d2dbd69463569c9cb0c5779c47cb34f70ffe",
    rationale: "Introduces the first machine-readable Nessa contract manifest and validation gate.",
    compatibility: "No consumer runtime API changes; repository review governance becomes explicit.",
    migration: "All later transitions compare against this governed manifest and append new amendments.",
    supersedes: null,
    pullRequest: null,
  },
  {
    id: "AMEND-002",
    kind: "transition",
    contractId: "SRC-002",
    baseRevision: "41f9fe804cf4fc5dd887cb7642ac0bfa8d9a3e6e",
    targets: ["validation/exceptions.ts"],
    beforeFingerprint: "4beb348bbeaa1d82da83a9d49b58d2dbd69463569c9cb0c5779c47cb34f70ffe",
    afterFingerprint: "078a941c919a625be47f3abd40a1e61fdbc508b9b4c8206cc06104c1c518fe8a",
    rationale: "Retires the destructive Button dark-opacity exception after rendered accessibility checks proved that the override reduced text contrast below the required threshold.",
    compatibility: "Destructive Buttons now use the canonical opaque destructive token in both themes, preserving their public API while restoring accessible dark-mode contrast.",
    migration: "Consumers using the destructive Button variant receive the corrected semantic-token treatment automatically and do not need to change application code.",
    supersedes: null,
    pullRequest: null,
  },
  {
    id: "AMEND-003",
    kind: "transition",
    contractId: "A11Y-002",
    baseRevision: "a969e1a073043d0d34d1476deb0749697d7af435",
    targets: ["validation/nessa/check-metadata.ts"],
    beforeFingerprint: "078a941c919a625be47f3abd40a1e61fdbc508b9b4c8206cc06104c1c518fe8a",
    afterFingerprint: "8cb616c48a66a3e3008059733cd6d1857c9f04e349cd5916058d2f921d902a0f",
    rationale: "Extends focus-treatment accessibility scanning to composite components (packages/react/src/composites) so composed surfaces such as the AppShell dock resize separator are measured by the same A11Y-002 evidence gate as the primitives, and corrects the storybook-coverage input declaration to the files that check actually reads (the package index and story files) now that coverage derives from public module exports.",
    compatibility: "Strictly widens accessibility validation coverage and tightens Storybook coverage to every component and composite module the package index exports, including directory modules the previous file-glob loop silently skipped; lib modules remain outside story coverage, and there are no consumer runtime API changes and no weakening of any existing requirement.",
    migration: "New composite components must register their focus treatments in validation/nessa/focus-treatments.ts exactly as component primitives already do, and every component or composite module exported from packages/react/src/index.ts must ship a matching Storybook story file.",
    supersedes: null,
    pullRequest: null,
  },
  {
    id: "AMEND-004",
    kind: "transition",
    contractId: "INT-001",
    baseRevision: "f792709798fc10e4923f52077ed096611a7850e5",
    targets: ["validation/contracts.ts", "validation/nessa/check-metadata.ts"],
    beforeFingerprint: "8cb616c48a66a3e3008059733cd6d1857c9f04e349cd5916058d2f921d902a0f",
    afterFingerprint: "f1496eff9e0b91537ee5aa395e43704e81623c50f1f5338fb472c282e7b4d435",
    rationale: "Adds an enforced interaction-stability check for ModelPicker so hover and focus previews cannot move the option hit-target surface that produced them.",
    compatibility: "Adds validation and Storybook evidence for a new component family without weakening existing AppShell, SplitView, theme, registry, or accessibility requirements.",
    migration: "ModelPicker implementations keep preview-dependent content out of option-flow geometry and maintain the focused narrow-viewport interaction story.",
    supersedes: null,
    pullRequest: null,
  },
  {
    id: "AMEND-005",
    kind: "transition",
    contractId: "A11Y-002",
    baseRevision: "074c6de966fa2c603d1e6eec3dd7bc37bab4e077",
    targets: ["validation/exceptions.ts"],
    beforeFingerprint: "f1496eff9e0b91537ee5aa395e43704e81623c50f1f5338fb472c282e7b4d435",
    afterFingerprint: "22709c0ab698f9ec6303b75205b58bedad282f42f2557a1afa522ad90ea50549",
    rationale: "Re-fingerprints the ledgered focus-contrast exceptions after the core palette moved from blue-tinted tokens to the neutral shadcn scale; every excepted combination still fails its required ratio for the same reason, only the measured token and surface values changed.",
    compatibility: "No exception is added or removed and no requirement weakens; the same subtle focus-tint failures remain ledgered with their measurements updated to the neutral palette.",
    migration: "None for consumers; hosts overriding theme tokens keep their own responsibility for focus contrast on custom surfaces.",
    supersedes: null,
    pullRequest: null,
  },
  {
    id: "AMEND-006",
    kind: "transition",
    contractId: "STYLE-001",
    baseRevision: "797c59bf8c85ec3dc6c3d50096b9ddf363afd698",
    targets: ["validation/contracts.ts", "validation/exceptions.ts", "validation/nessa/check-metadata.ts"],
    beforeFingerprint: "22709c0ab698f9ec6303b75205b58bedad282f42f2557a1afa522ad90ea50549",
    afterFingerprint: "949e200a1041173b0ceafd3a9256b30cd6259a9ac95c8731f2f9b1fa98856f1e",
    rationale: "Adds three enforced styling-discipline contracts (STYLE-001 semantic-color-only class surfaces, STYLE-002 frozen stacking scale, STYLE-003 inline-style computed-geometry allowlist) with a new style-discipline checker, making token bypasses and unaudited inline styling structurally visible instead of convention-guarded; the checker covers .ts and .tsx class surfaces, named colors, paint arbitrary properties, dynamic style keys, and literal-color custom properties.",
    compatibility: "Strictly adds validation with no consumer runtime API changes; every existing off-scale stacking utility and out-of-allowlist inline style property is preserved verbatim as an exact ledgered occurrence, so no rendered output changes.",
    migration: "New code uses semantic token utilities for color, the z-0..z-50 scale for layering, and custom properties plus the geometry allowlist for runtime-computed inline styles; ledgered occurrences shrink toward zero under their recorded removal conditions and may never grow without an explicit amendment.",
    supersedes: null,
    pullRequest: null,
  },
  {
    id: "AMEND-007",
    kind: "transition",
    contractId: "TOKEN-004",
    baseRevision: "91d36961249868084406862adace9d9520bd1852",
    targets: ["validation/contracts.ts", "validation/nessa/check-metadata.ts"],
    beforeFingerprint: "949e200a1041173b0ceafd3a9256b30cd6259a9ac95c8731f2f9b1fa98856f1e",
    afterFingerprint: "dbbadc4c36c3c2329a059d255a1246a569876159bd27d9320de5ba4ea178fb6e",
    rationale: "Activates the coordinated typography levels and the constrained UI scale the core contract already specified but nothing implemented: text size was raw Tailwind, including five ad-hoc arbitrary values, so no consumer could change UI size and no gate could see the drift.",
    compatibility: "Strictly adds an enforced contract and its checker; every level reproduces the size the migrated utility rendered at scale 100, and the named Tailwind sizes also keep their line-height. The ad-hoc 11px surfaces (table headers, sort buttons, count badges) previously inherited whatever ratio surrounded them and now adopt level 1's coordinated 1.454545 line box — an intentional sub-2px metric correction, not parity. No existing requirement is weakened or excepted.",
    migration: "Nessa-owned components name a nessa-text level instead of a Tailwind size utility, using an em value only where a descendant selector cannot carry a helper class; applications opt into a different UI size by setting data-nessa-scale to one of the six presets on any wrapper element, which rescales type and spacing-derived control geometry together.",
    supersedes: null,
    pullRequest: null,
  },
  {
    id: "AMEND-008",
    kind: "transition",
    contractId: "PARSE-001",
    baseRevision: "b7e70bb1978337a35d8f5435e86c3b16f65c90d6",
    targets: ["validation/contracts.ts", "validation/nessa/check-metadata.ts"],
    beforeFingerprint: "dbbadc4c36c3c2329a059d255a1246a569876159bd27d9320de5ba4ea178fb6e",
    afterFingerprint: "bcd57383ecd6ab2c42f2eaf5480642f42747767794eb485bf26fbc36ae3ce5eb",
    rationale: "Nessa now ships parsers that read untrusted bytes from a third-party CLI whose shapes change between releases, and the three failure modes that surface introduces are all silent: a TypeScript enum cannot hold a value decoded from JSON without a cast, an exported vocabulary that is only `as const` is mutable at runtime, and hand-rolled `typeof` narrowing drifts until a malformed line becomes a crash or a wrong value rather than an absent one. PARSE-001, PARSE-002 and PARSE-003 make each structurally visible; the checker caught seven violations in the parser that introduced it.",
    compatibility: "Strictly adds validation with no consumer runtime API change and no rendered output change. The rules are scoped to packages/react/src/lib/agent-stream, and test files are exempt from PARSE-003 because asserting a runtime shape there is the assertion rather than a narrowing shortcut. No existing requirement is weakened, and the contracts carry no exception ledger.",
    migration: "New parser code declares wire vocabularies as Object.freeze objects with derived unions, exports them frozen, and narrows every decoded value through the shared readers in lib/agent-stream/json.ts. A second provider inherits the same three rules by living under the same path.",
    supersedes: null,
    pullRequest: null,
  },
  {
    id: "AMEND-009",
    kind: "transition",
    contractId: "PKG-001",
    baseRevision: "0f38c0985c4d3e9c8c6afc5fb6324f5c2cfd60e7",
    targets: ["validation/contracts.ts", "validation/nessa/check-metadata.ts"],
    beforeFingerprint: "bcd57383ecd6ab2c42f2eaf5480642f42747767794eb485bf26fbc36ae3ce5eb",
    afterFingerprint: "d738b3180ff85f50d0bbf8e63b44fd76aca89f6d1816c67d5c813eb58c3685c5",
    rationale: "The parser was framework-free in its source and not in what it shipped: reaching it meant installing @nessa-ui/react, so a Node process or server component took a react >=19 peer, a rendering tree (mermaid, katex, react-markdown, radix), and a \"use client\" directive stamped onto every built module by the package's own build. The architecture doc's rule that no component may read the wire was therefore advisory, enforced by nothing. Extracting packages/agent-stream makes the layering a package boundary, and splitting its exports at the contract makes \"the parser stops at the agent message\" a fact a check can read: the main entry carries wire and mapper, the ./transcript subpath carries the optional fold.",
    compatibility: "No rendered output change, and no API change for the npm consumer: @nessa-ui/react re-exports both entries, so its public surface is byte-for-byte what it was, the two star-exports being safe only because the entries are disjoint. The shadcn registry consumer is a breaking change and is not covered by that: a project that copied lib/agent-stream and imported the fold from the barrel loses seventeen symbols from it, because the copied index.ts is now the contract entry and no exports map exists in copied source to route the subpath. The fold moves to lib/agent-stream/transcript/, so a deep import of lib/agent-stream/transcript keeps resolving and gains TranscriptBuilder; a deep import of lib/agent-stream/builder does not. Stable install paths were not stable API and the distinction is recorded here rather than implied. PARSE-001's rules are unchanged and follow their sources to the new location, with the wire.ts narrowing exemption matching exactly the one file it matched before. PKG-001 and PKG-002 are restated to cover both published packages rather than only the React one, and their authority section gains a parser subsection, so the parser findings are appealable to text that governs them; PKG-003 is restated for the same reason. No existing requirement is weakened, and no exception is added.",
    migration: "Parser code lives in packages/agent-stream/src and may declare no dependencies, no peers, no React import, and no client directive; the contract entry may not reach packages/agent-stream/src/transcript/ by re-export or through any transitive relative import, which the package-artifacts check walks rather than assumes. A host that wants only the event log imports @nessa-ui/agent-stream; one that wants the default turns-and-groups shape also imports @nessa-ui/agent-stream/transcript. New code imports the package directly rather than through @nessa-ui/react, which re-exports it for compatibility. A registry consumer that imported the fold from lib/agent-stream changes that import to lib/agent-stream/transcript.",
    supersedes: null,
    pullRequest: null,
  },
  {
    id: "AMEND-010",
    kind: "correction",
    contractId: "PKG-002",
    baseRevision: "98b5604",
    targets: [],
    beforeFingerprint: "d738b3180ff85f50d0bbf8e63b44fd76aca89f6d1816c67d5c813eb58c3685c5",
    afterFingerprint: "d738b3180ff85f50d0bbf8e63b44fd76aca89f6d1816c67d5c813eb58c3685c5",
    rationale: "AMEND-009 recorded two things that are no longer true of the code, and the ledger is the wrong place to leave a false statement standing. It said a shadcn consumer loses seventeen fold symbols because the copied index.ts is now the contract entry: the contract entry moved to contract.ts and index.ts became a barrel re-exporting contract and transcript, so the registry consumer's surface is whole again and the published package still splits. It also said the wire.ts narrowing exemption matched exactly the one file it matched before: that exemption is deleted, because PARSE-001 and PARSE-003 pass without it and no wire has ever needed it. Correcting rather than rewriting, because AMEND-009 was accurate about its own transition and the history is append-only.",
    compatibility: "No governed source changed, so the snapshot fingerprint is unmoved and this correction records a fact rather than a transition. The registry change restores API that AMEND-009's transition removed, which is additive for every consumer and reverts none of that transition's other effects. Deleting the narrowing exemption strengthens PARSE-003's enforced surface rather than weakening it: nothing was excepted before this and nothing is excepted after, and the contracts carry no exception ledger entry either way.",
    migration: "A registry consumer that migrated an import from lib/agent-stream to lib/agent-stream/transcript on AMEND-009's advice may keep it — the deep path still resolves — or move it back to the barrel; both work. New parser wires narrow through the shared readers with no path-granted exemption available.",
    supersedes: "AMEND-009",
    pullRequest: null,
  },
])
